import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// const roboto = Roboto({ subsets: ["latin"] });
const roboto = Roboto({
  weight: '400', // Geçerli ağırlıklardan birini seçin
  subsets: ['latin'], // Kullandığınız alt kümeleri belirtin
});

export const metadata = {
  title: "sahibinden.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
