import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { createClient } from "./utils/supabase/server";





const lexend = Lexend({
  weight: '400', 
  subsets: ['latin'], 
});

export const metadata = {
  title: "Gamekeybox.com",
  description: "Generated by create next app",
  icons:{
    icon:  [
      {
        media: "(prefers-color-scheme: light)",
        url: "favion.ico",
        href: "favicon.ico"
      }
    ]
  }
};

export default async function RootLayout({ children }) {

  const supabase = createClient(); 
  const { data, error } = await supabase.auth.getUser(); 
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Header   user={data?.user} />
        {children}
      </body>
    </html>
  );
}
