import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// const roboto = Roboto({ subsets: ["latin"] });
const roboto = Roboto({
  weight: '400', // Geçerli ağırlıklardan birini seçin
  subsets: ['latin'], // Kullandığınız alt kümeleri belirtin
});

export const metadata = {
  title: "Gamebox.com",
  description: "Generated by create next app",
  icons:{
    icon:  [
      {
        media: "(prefers-color-scheme: light)",
        url: "favion.ico",
        href: "favicon.ico"
      }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
